name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up V version latest
        uses: nocturlab/setup-vlang-action@v1
        with:
          id: v
          v-version: master

      - name: Build linux binaries
        run: |
          .github/workflows/set_version.sh
          make bin/vsql

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            elliotchance/vsql
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: elliotchance
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
